### ISSUE TITLE
q1, Median, q3 Decimal Precision 

### ISSUE THREAD

**Issue by HamsalekhaHR** [datavisyn/chartjs-chart-box-and-violin-plot#56]
Team, 

Please suggest how to set decimal place precision to required no. Attached is the screen shot of recurring precision value 
![BoxPlot_DecimalPlacePrecision_Issue](https://user-images.githubusercontent.com/55982503/68202474-d3f4a800-ffe9-11e9-90a9-c60be8505ad8.jpg)

**Comment by sgratzl** [comment]
take a look at https://codepen.io/sgratzl/pen/yLLKNwR?editors=0010

![image](https://user-images.githubusercontent.com/4129778/68212154-f5807000-ffa6-11e9-93aa-ee62dd29f316.png)

you can configure it using the `tooltipDecimals` option key

**Comment by HamsalekhaHR** [comment]
Implemented below steps
1- After adding tooltipDecimals getting following error 
**Object literal may only specify known properties, and 'tooltipDecimals' does not exist in type 'ChartOptions'.**
2- Also tried upgrading chart.js but no luck, graph threw an error of minBarLength, hence rolled back to chart.js2.8.0

In codepen, tooltipdecimals works fine but not with my code.. What are the version used in codepen. Please suggest...

**Comment by sgratzl** [comment]
> Object literal may only specify known properties, and 'tooltipDecimals' does not exist in type 'ChartOptions'.

looks like you are using TypeScript. Well, this plugin is not providing any type extensions to Chart.js types thus the compiler complains about the unknown property `tooltipDecimals`. I think the only way is to cast the whole options object to any to fix this atm.

**Comment by HamsalekhaHR** [comment]
True, Using this Box plot package with angular 7...

**Comment by sgratzl** [comment]
@HamsalekhaHR any updates? if it works, please close this issue

**Comment by HamsalekhaHR** [comment]
@sgratzl , should I update npm package or any specific development branch version because in npm boxplot site last release was 7 months age.. please suggest

**Comment by sgratzl** [comment]
I just released version v2.2.0 you you should be able to just install it via npm

**Comment by HamsalekhaHR** [comment]
@sgratzl -> issue still exists even after upgrading boxplot plugin to v2.2.0
![image](https://user-images.githubusercontent.com/55982503/69405106-dd3d7e80-0d24-11ea-884c-3853bdd6e269.png)

**Comment by sgratzl** [comment]
> @sgratzl -> issue still exists even after upgrading boxplot plugin to v2.2.0

yes I haven't had time yet to do #57. As I said for now you have to cast it to any
